version: '3'
services:
  pacsdb:
    image: postgres:12.2
    container_name: pacsdb
    environment:
      POSTGRES_DB: conquestdb
      POSTGRES_USER: conquestuser
      POSTGRES_PASSWORD: conquestpass
    networks:
      - dcmnet

  dicomsrv:
    build:
      context: ./
      args:
        DBMS: postgres
    image: iarkin/conquest-postgres:v1.15.0_3.1
    container_name: dicomsrv
    depends_on:
      - pacsdb
    ports:
      - '104:5678'
    environment:
      AE_TITLE: DICOMSRV
      SQL_HOST: pacsdb
      DB_NAME: conquestdb
      DB_USERNAME: conquestuser
      DB_PASSWORD: conquestpass
      INCOMING_COMPRESSION: un
      FILE_NAME_SYNTAX: 6
    volumes:
      - /srv/data/images/:/opt/conquest/data
    networks:
      - dcmnet

networks:
  dcmnet:
    external:
      name: dcmnet
