version: '2.2'
services:
  pacsdb:
    image: postgres:11
    container_name: pacsdb
    environment:
      POSTGRES_DB: conquestdb
      POSTGRES_USER: conquest
      POSTGRES_PASSWORD: conquestpass
    networks:
      - dcmnet

  dicomsrv:
    build:
      context: ./dicomsrv
    image: dicomsrv:v19c1
    container_name: dicomsrv
    depends_on:
      - pacsdb
    ports:
      - '104:5678'
    environment:
      SQL_CONTAINER_NAME: pacsdb
      DB_NAME: conquestdb
      DB_USERNAME: conquest
      DB_PASSWORD: conquestpass
    volumes:
      - /srv/data/images/:/opt/conquest/data
    networks:
      - dcmnet
      
networks:
  dcmnet:
    external:
      name: dcmnet
