version: '2.2'
services:
  pacsdb:
    image: postgres:9.6
    container_name: pacsdb
    environment:
      POSTGRES_DB: conquestdb
      POSTGRES_USER: conquest
      POSTGRES_PASSWORD: conquestpass
  dicomsrv:
    build:
      context: ./conquest
      network: host
    image: dicomsrv
    depends_on:
      - pacsdb
    ports:
      - '104:5678'
    volumes:
      - ./conquest/data:/opt/conquest/data
  wado:
    build:
      context: ./wado
      network: host
    image: wado
    depends_on:
      - dicomsrv
    expose:
      - "80"
#  viewer:
#    build:
#      context: ./oviyam
#      network: host
#    image: viewer
#    depends_on:
#      - wado
#    expose:
#      - "8080"
#      - "1025"
#    ports:
#      - '8081:8080'
